name: Run E2E flow
on: ["push"]
jobs:
  build:
    name: Deploy Application and Run API and UI Test cases   
    runs-on: ubuntu-latest       
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Project dependencies 
      run: yarn
    - name: Start Backend application
      run: yarn start:backend:ci
    - name: Start Frontend application
      run: yarn start:frontend:ci
    - name: Start  Backend API Test cases
      if: succeeded() || failed()
      run: yarn test:backend
    - name: Start  Frontend UI Test cases
      if: succeeded() || failed()
      run: yarn test:frontend
